# Welcome to Velatryx's Personal Website!
title: /Velatryx
email:
description: A curious creature who just created the website. # this means to ignore newlines until "baseurl:"
  
github_username: Velatryx
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Murax"
  avatar : "/assets/images/5da04febe5b62a26d86eb52524ddd4c7.jpg"
  bio    : "A curious creature who just created this website!"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "tryhackme"
      icon: "'<img src="/assets/img/Tryhackme--Streamline-Simple-Icons.png" alt="THM" style="height:20px;">'"
      url: "https://tryhackme.com/p/hoaX"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Velatryx"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: ""

footer:
  links:
    - label: "tryhackme"
      icon: "'<img src="/assets/img/Tryhackme--Streamline-Simple-Icons.png" alt="THM" style="height:20px;">'"
      url: "https://tryhackme.com/p/hoaX"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Velatryx"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: ""

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
